### PR TITLE
Config file support (parameter -c)

### PR DESCRIPTION
**Pull request by relet**
JSON configuration file support for data-exporter. See files/metadata-exporter.conf.example
Do not merge yet. Some work still required to get the -h parameter to work again.

### CODE REVIEW

**Comment by kristrev** [comment]
Lets make it easy. Lets remove the dynamic part of help and print the text of all compiled modules.

**Comment by relet** [comment]
I was hoping you'd say that. ;) We can still generate it from the individual methods.

**Comment by relet** [comment]
Ok, changed the help to include all compile time modules, and explain the JSON syntax instead. 
Confirmed to work #ifdef MONROE, you should check #ifdef OPENWRT

**Comment by kristrev** [comment]
I guess this can just be merged? Code will work also with existing paramteres, right?

**Comment by relet** [comment]
No, the parameters have been removed, with the exception of -h and -c. That
is because each input and writer had its own method to handle
configuration, reading from args before and reading from the JSON struct
after.

**Comment by kristrev** [comment]
Ok. Merge will have to be postponed until after we are done with API v2.

**Comment by kristrev** [comment]
Please fix conflict and this is ready to merge, I will just freeze the routers on an older commit.

**Comment by relet** [comment]
Ok

**Comment by relet** [comment]
Merged.

**Pull request merged**
